// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6-0o-ZmGo2dRVRHqchHrrraM0pAdkVM',
    appId: '1:660185013480:web:8fc006f364736e75a2fd5d',
    messagingSenderId: '660185013480',
    projectId: 'employee-track-expense-ff6f3',
    authDomain: 'employee-track-expense-ff6f3.firebaseapp.com',
    storageBucket: 'employee-track-expense-ff6f3.firebasestorage.app',
    measurementId: 'G-X9S7NPCCBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNKBwxxghBVvZ6jNpCDizFwOZq_c1SW2I',
    appId: '1:660185013480:android:dc8e24819c125386a2fd5d',
    messagingSenderId: '660185013480',
    projectId: 'employee-track-expense-ff6f3',
    storageBucket: 'employee-track-expense-ff6f3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW6-0o-ZmGo2dRVRHqchHrrraM0pAdkVM',
    appId: '1:660185013480:web:ee6a46d8f1bbab2ca2fd5d',
    messagingSenderId: '660185013480',
    projectId: 'employee-track-expense-ff6f3',
    authDomain: 'employee-track-expense-ff6f3.firebaseapp.com',
    storageBucket: 'employee-track-expense-ff6f3.firebasestorage.app',
    measurementId: 'G-SZ0QJFVDMZ',
  );
}
